### ISSUE TITLE
Research about camera sensor capabilities

### ISSUE THREAD

**Issue by mche3kek** [feedme-swent-epfl/feedme-android#11]
Investigate the scanning possibilities of the camera sensor with regard to barcode scanning, OCR (Optical Character Recognition), image recognition. What's the feasibility of each ? Resources ? Difficulty + time estimates ?

**Deliverable :** wiki article with research contents

**Comment by fdejean** [comment]
I started doing a draft [wiki](https://www.notion.so/mriwa/Backend-5922beb3c12845aaad71742e088e4ca9)  on the notion.

Firebase provide freely the following
- Barcode scanning
- text recognition
- image labeling
- translation

I will do some more research and some testing to see viable those tools can be for our app.

**Comment by ohamz** [comment]
I added info on the [Notion](https://www.notion.so/mriwa/Backend-Sensor-5922beb3c12845aaad71742e088e4ca9) and the [Github Wiki](https://github.com/feedme-swent-epfl/feedme-android/wiki/Research-Info) (under Android Camera API) for implementing the Camera itself within the app and taking pictures.
Will work on the UI in the coming days, will open a pull request once started.

Once we have the base we can extend it to analyze the pictures taken using AI (Google ML Kit).

**Comment by mche3kek** [comment]
Issue is finished
