### ISSUE TITLE
Design user flows for the application

### ISSUE THREAD

**Issue by mche3kek** [feedme-swent-epfl/feedme-android#12]
Design several well-defined user flows along with regard to our user stories

  - feedme-swent-epfl/feedme-android#13
  - feedme-swent-epfl/feedme-android#14
  - feedme-swent-epfl/feedme-android#15

**Comment by mche3kek** [comment]
Child issues still not closed

**Comment by FacerOfGod** [comment]
Oups sorry for me both child issues are finished and completed.
We have elaborated all the user stories and all the user flows have been made in Figma.
Why do you think these issues aren't finished ?

**Comment by mche3kek** [comment]
For issue 13 we still need to convert them into Product Backlog items for the SCRUM board, I assigned myself so I can do that today.

As for issue 15, I just saw that it was still not closed, so I assumed it was not finished

**Comment by JeannedeM** [comment]
All sub issues are finished now.
