### ISSUE TITLE
Draft and choose user flows

### ISSUE THREAD

**Issue by mche3kek** [feedme-swent-epfl/feedme-android#14]
Design a few coherent and well defined user flows for our app and choose the best two to three ones for implementation. Sketch on paper the flows for better visualization.

**Comment by JeannedeM** [comment]
We finished the design of users flows today.

**Comment by mche3kek** [comment]
Here are the [User Flows](https://github.com/feedme-swent-epfl/feedme-android/wiki/User-Flows) we designed following our collective brainstorming session
