### ISSUE TITLE
Reflexion on how to uniformize the ingredients inputted in the FindRecipe page 

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#145]
Goals : 

- Make research on UI we wanna do for input ingredients through camera.
- Make propositions on Figma.

**Comment by xrsula** [comment]
The figma reprensentation of how to scan ingredients to generate recipes is fully implemented (cf the screen recording down here)

https://github.com/feedme-swent-epfl/feedme-android/assets/100283160/95d3fa72-979d-41fe-a512-bbf132173163
