### ISSUE TITLE
Design the chosen user flows on Figma

### ISSUE THREAD

**Issue by mche3kek** [feedme-swent-epfl/feedme-android#15]
Design the chosen user flows on Figma with the different possible paths, trying to be as exhaustive as possible

**Comment by JeannedeM** [comment]
![Image](https://github.com/feedme-swent-epfl/feedme-android/assets/94188707/128d66bb-14e1-4205-bf9e-5d16e6ee80d3)

First draft of the landing page on figma done.

**Comment by 0marwa** [comment]
[A prototype of the user flows designed so far ](https://www.figma.com/proto/ZUozRJOdgMsRiBk9FnqxJS/Main_FeedMe?type=design&node-id=57-54&t=BUsQBZE6PShEBSxR-1&scaling=scale-down&page-id=0%3A1&starting-point-node-id=57%3A54&mode=design)

**Comment by FacerOfGod** [comment]
Most user flows how been made.
However works still needs to be done with the UI

**Comment by JeannedeM** [comment]
After this meeting we are happy with what we have done in Figma. Small adjustement still needs to be done but we will create a new issue for that.
