### ISSUE TITLE
Add tags for recipe difficulty on recipe cards

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#198]
In our recipes we have a difficulty each time. The goal is to add a "tag" with difficulty on recipes.

Tasks : 

- [x] Check in fetched recipes how many levels of difficulty exists -> maybe think about a specific color for each one.
- [ ] Create UI for this tag.
- [ ] Implement this tag on recipe cards.
- [ ] Implement this tag on full recipe display page.
- [ ] Maybe : implement this tag on recipe thumbnail in profile page. (Just see if there is enough space to display this).

**Comment by 0marwa** [comment]
I will also implement the fetching of the difficulty tags from the database and the display because no one is assigned the backend issue so far :)
