### ISSUE TITLE
Design architecture diagram for our application

### ISSUE THREAD

**Issue by mche3kek** [feedme-swent-epfl/feedme-android#20]
Architecture diagram : What is it ? How to design one ? Constraints by given model for the app ? Template / existing models to draw inspiration from ?

Design architecture diagram for our application (Split App Model)

**Comment by fdejean** [comment]
Hello, yes, as we discuss our data model will look like this

![Image](https://github.com/feedme-swent-epfl/feedme-android/assets/73421792/12e41d06-ea3a-4391-9948-0cf66cb48773)

#23 was used to quickly let the model be accessible for the UI.
I will keep working on the same branch once it's merge with main to implement the database.

**Comment by fdejean** [comment]
Same Issue as #18

**Comment by JeannedeM** [comment]
![Image](https://github.com/feedme-swent-epfl/feedme-android/assets/94188707/2e0a5e05-7c71-414e-a3eb-599bc816e147)

**Comment by mche3kek** [comment]
Architecture diagram improved upon and completed, opening a new branch for merge to main
