### ISSUE TITLE
Research : do we add handwritten recognition or image recognition in ML part

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#200]
Do quick research to evaluate which option we choose : 

1. We do not add additionnal ML method to the app.
2. We add handwritten text recognition.
3. We add image labelling and ingredient extraction from image.

**Comment by JeannedeM** [comment]
Research results (summary) : 

- Handwrittent detection will not be possible using google ML kit, it only accepts handwritten text on a digital device (ie not a phtoto of a paper). 
- Image labelling could be possible but would involved at least 15-20 hours of work.

**Comment by xrsula** [comment]
This issue is closed successfuly since we are able to use image recognition and handwriting recognition
