### ISSUE TITLE
UI : add profile picture of user in the settings screen

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#214]
In the settings screen, the user profile picture is currently a place holder.

- [ ] UI : upload user profile picture in the settings screen.

![Image](https://github.com/feedme-swent-epfl/feedme-android/assets/94188707/999117b6-eecc-4252-a5e6-31e8b2223d43)

**Comment by mche3kek** [comment]
This issue was solved and closed during PR #254
