### ISSUE TITLE
Bug : app navigation

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#220]
Update (more isolated bug) : 
1. Open app
2. Login
3. Click on a recipe Card -> you arrive on full recipe display
4. Click on the "home button" in the bottom bar -> **CRASH** (it should bring you back to landing page).

_Bug description (old version) :_

_1. Open app
2. Login
3. Click on a recipe Card
4. Click on the user name (who posted the recipe) -> you arrive on its profile page.
5. Click on the back arrow -> you come back to the full recipe display.
6. Click on the "home button" in the bottom bar -> **CRASH** (it sould bring you back to landing page)._

**Comment by ohamz** [comment]
@JeannedeM I think this bug was fixed in another, can you confirm ?

**Comment by ohamz** [comment]
This bug was linked to another bug that was fixed in another issue.
