### ISSUE TITLE
Bug : text recognition

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#221]
Bug description : 

1. Open the app
2. Login
3. Click on "fork and knife button" in the bottom bar -> you arrive on input ingredients screen
4. Click on photo floating button -> you arrive on camera screen
5. Click on photo button (take a picture of a list of ingredients, for example, see the one below)
6. Click on text recognition button.
7. You get the error "Failed to extract ingredients from text"
8. Click again on text recognition button -> you get zero error but no green message (which means that exactly the same error occurs a second time).

**Comment by FacerOfGod** [comment]
It's works on the emulator on the main branch.

I think this bug seems to be linked to the APK and GitHub secrets not fetching the API key correctly.

**Comment by JeannedeM** [comment]
After testing on the last apk, it works as well. Problem solved.
