### ISSUE TITLE
Work on scenario of demo

### ISSUE THREAD

**Issue by 0marwa** [feedme-swent-epfl/feedme-android#239]
Some of the main features to be included in the demo : 

- [ ] generate recipe
- [ ] save recipe
- [ ] offline mode quand tu save un recette
- [ ] leave comment
- [ ] follow la personne qui a fait le recipe
- [ ] faire le user flow qui permet d'add une recipe (vite fait)

Link to the [elevator pitch](https://docs.google.com/document/d/1IR_8hDcOJr1RcHNkYOVSFm7BqMARJ5xE8g3jwHWlXu8/edit?usp=sharing)

**Comment by mche3kek** [comment]
Demo is done, we finished 2nd :yay:
