### ISSUE TITLE
Small UI fixes part 2

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#257]
Tasks : 

- [x]     Remove share button on profile page.
- [x]     Fix long name problem on profile page.
- [x]     Find better positon for user name on recipe card.
- [x]     Fix UI of recipe manual input.
- [x]     Improve add floating button on profile page.
- [x]      Fix profile picture UI in profile screen.

**Comment by xrsula** [comment]
I am picking up this issue from Jeanne since I have more time to do it :)
