### ISSUE TITLE
UI for Recipes comments page

### ISSUE THREAD

**Issue by JeannedeM** [feedme-swent-epfl/feedme-android#60]
Design the UI for the recipe comments page. The page should look like this screen : 

![Image](https://github.com/feedme-swent-epfl/feedme-android/assets/94188707/156cae3d-a01a-472d-b9ce-39b04f00eb38)

This should reuse the comments thumbNails implemented last week

**Comment by xrsula** [comment]
This issue has been removed from the SCRUM board since it has been dealt with in another PR / issue
